export const TABLE_CONFIG = {
  clientes: {
    columns: [
      "id",
      "nome",
      "cnpj",
      "endereco",
      "colaborador_responsavel",
      "valor_mensal",
      "dados_pagamento",
      "email",
      "telefone",
      "whatsapp_phone",
      "onboarding_status",
      "onboarding_status_at",
      "drive_folder_id",
      "drive_folder_url",
      "drive_folder_created_at",
      "created_at",
      "updated_at",
    ],
    insertColumns: [
      "nome",
      "cnpj",
      "endereco",
      "colaborador_responsavel",
      "valor_mensal",
      "dados_pagamento",
      "email",
      "telefone",
      "whatsapp_phone",
      "onboarding_status",
      "onboarding_status_at",
      "drive_folder_id",
      "drive_folder_url",
      "drive_folder_created_at",
    ],
    updateColumns: [
      "nome",
      "cnpj",
      "endereco",
      "colaborador_responsavel",
      "valor_mensal",
      "dados_pagamento",
      "email",
      "telefone",
      "whatsapp_phone",
      "onboarding_status",
      "onboarding_status_at",
      "drive_folder_id",
      "drive_folder_url",
      "drive_folder_created_at",
    ],
  },
  cliente_servicos: {
    columns: ["id", "cliente_id", "servico_id", "created_at"],
    insertColumns: ["cliente_id", "servico_id"],
    updateColumns: [],
  },
  servicos: {
    columns: [
      "id",
      "nome",
      "categoria",
      "preco",
      "status",
      "contratos",
      "tendencia",
      "descricao",
      "arquivo_url",
      "created_at",
      "updated_at",
    ],
    insertColumns: [
      "nome",
      "categoria",
      "preco",
      "status",
      "contratos",
      "tendencia",
      "descricao",
      "arquivo_url",
    ],
    updateColumns: [
      "nome",
      "categoria",
      "preco",
      "status",
      "contratos",
      "tendencia",
      "descricao",
      "arquivo_url",
    ],
  },
  comercial_metas: {
    columns: ["id", "vendedor", "meta", "realizado", "canal", "periodo", "created_at", "updated_at"],
    insertColumns: ["vendedor", "meta", "realizado", "canal", "periodo"],
    updateColumns: ["vendedor", "meta", "realizado", "canal", "periodo"],
  },
  comercial_oportunidades: {
    columns: [
      "id",
      "cliente",
      "valor",
      "etapa",
      "responsavel",
      "dias_parado",
      "observacao",
      "created_at",
      "updated_at",
    ],
    insertColumns: ["cliente", "valor", "etapa", "responsavel", "dias_parado", "observacao"],
    updateColumns: ["cliente", "valor", "etapa", "responsavel", "dias_parado", "observacao"],
  },
  marketing_redes: {
    columns: [
      "id",
      "plataforma",
      "seguidores",
      "engajamento",
      "posts_semana",
      "crescimento",
      "username",
      "created_at",
      "updated_at",
    ],
    insertColumns: ["plataforma", "seguidores", "engajamento", "posts_semana", "crescimento", "username"],
    updateColumns: ["plataforma", "seguidores", "engajamento", "posts_semana", "crescimento", "username"],
  },
  cronograma_conteudo: {
    columns: ["id", "dia", "tipo", "descricao", "rede", "created_at", "updated_at"],
    insertColumns: ["dia", "tipo", "descricao", "rede"],
    updateColumns: ["dia", "tipo", "descricao", "rede"],
  },
  onboarding_sessions: {
    columns: [
      "id",
      "phone_e164",
      "tracking_token",
      "cliente_id",
      "current_status",
      "status_updated_at",
      "last_message_at",
      "last_provider_message_id",
      "cliente_snapshot",
      "last_payload",
      "created_at",
      "updated_at",
    ],
    insertColumns: [
      "phone_e164",
      "tracking_token",
      "cliente_id",
      "current_status",
      "status_updated_at",
      "last_message_at",
      "last_provider_message_id",
      "cliente_snapshot",
      "last_payload",
    ],
    updateColumns: [
      "cliente_id",
      "current_status",
      "status_updated_at",
      "last_message_at",
      "last_provider_message_id",
      "cliente_snapshot",
      "last_payload",
    ],
  },
  onboarding_messages: {
    columns: ["id", "session_id", "provider_message_id", "direction", "payload", "event_timestamp", "created_at"],
    insertColumns: ["session_id", "provider_message_id", "direction", "payload", "event_timestamp"],
    updateColumns: [],
  },
  onboarding_status_history: {
    columns: ["id", "session_id", "from_status", "to_status", "reason", "provider_message_id", "changed_at"],
    insertColumns: ["session_id", "from_status", "to_status", "reason", "provider_message_id", "changed_at"],
    updateColumns: [],
  },
  relevo_dates: {
    columns: ["id", "cliente_id", "phone_e164", "relevo_date", "tipo", "timezone", "ativo", "created_at", "updated_at"],
    insertColumns: ["cliente_id", "phone_e164", "relevo_date", "tipo", "timezone", "ativo"],
    updateColumns: ["cliente_id", "phone_e164", "relevo_date", "tipo", "timezone", "ativo"],
  },
  reminder_logs: {
    columns: [
      "id",
      "cliente_id",
      "phone_e164",
      "relevo_date",
      "tipo",
      "status",
      "provider_message_id",
      "sent_at",
      "error_summary",
      "payload",
      "created_at",
    ],
    insertColumns: [
      "cliente_id",
      "phone_e164",
      "relevo_date",
      "tipo",
      "status",
      "provider_message_id",
      "sent_at",
      "error_summary",
      "payload",
    ],
    updateColumns: ["status", "provider_message_id", "sent_at", "error_summary", "payload"],
  },
  operational_items: {
    columns: [
      "id",
      "idempotency_key",
      "tipo",
      "titulo",
      "descricao",
      "cliente_id",
      "responsavel",
      "prioridade",
      "status",
      "prazo_at",
      "detalhes",
      "trello_card_id",
      "trello_card_url",
      "trello_list_id",
      "created_at",
      "updated_at",
    ],
    insertColumns: [
      "idempotency_key",
      "tipo",
      "titulo",
      "descricao",
      "cliente_id",
      "responsavel",
      "prioridade",
      "status",
      "prazo_at",
      "detalhes",
      "trello_card_id",
      "trello_card_url",
      "trello_list_id",
    ],
    updateColumns: [
      "idempotency_key",
      "tipo",
      "titulo",
      "descricao",
      "cliente_id",
      "responsavel",
      "prioridade",
      "status",
      "prazo_at",
      "detalhes",
      "trello_card_id",
      "trello_card_url",
      "trello_list_id",
    ],
  },
};
